version: "3"
services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-maestro
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=replica

  mysql-esclavo:
    image: mysql:8.0
    container_name: mysql-esclavo
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: replica
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=replica


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-master, mysql-slave
      PMA_ARBITRARY: 1

    


 