version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx12
    ports:
     - 8081:80

  apache:
    image: httpd:latest
    container_name: apache12
    ports:
     - 8082:80
     
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin12
    ports:
     - 8083:80
  #   environment:
  #    - PMA_ARBITRARY=1
  #    - PMA_HOST=

  servidor1:
    build:
      context: ./servidor1
      dockerfile: Dockerfile
    container_name: servidor1
    ports:
     - 8084:5002  
 
  servidor2:
    build:
      context: ./servidor2
      dockerfile: Dockerfile
    container_name: servidor2
    ports:
     - 8085:5003  
    volumes:
    # Ruta del host:Ruta del contenedor
      - ./datos:/app/data 

  servidor3:
    build:
      context: ./servidor3
      dockerfile: Dockerfile
    container_name: servidor3
    ports:
     - 8086:5004  

volumes:
  datos:      
 