version: '3'
services:
  servidor1:
    build: 
      context: ./Servidor1  # Ajusta la ruta a la carpeta correcta
      dockerfile: Dockerfile
    container_name: servidor1
    ports:
      - 5001:5000
    networks:
      - app-network  # Definir la red común

  servidor2:
    build: 
      context: ./Servidor2  # Ajusta la ruta a la carpeta correcta
      dockerfile: Dockerfile
    container_name: servidor2
    ports:
      - 5002:5000
    networks:
      - app-network  # Definir la red común

  servidor3:
    build: 
      context: ./Servidor3  # Ajusta la ruta a la carpeta correcta
      dockerfile: Dockerfile
    container_name: servidor3
    ports:
      - 5003:5000
    networks:
      - app-network  # Definir la red común

  nginx:
    build: 
      context: ./nginx  # Ajusta la ruta a la carpeta correcta
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - app-network  # Definir la red común
    depends_on:
      - servidor1
      - servidor2
      - servidor3

networks:
  app-network:  # Define la red donde los contenedores estarán conectados
    driver: bridge  # Usa el controlador predeterminado de Docker
